### ISSUE TITLE
can't import project

### ISSUE THREAD

**Issue by jemshit** [StevenByle/Android-Material-Themes-Demo#8]
i cloned the project but android studio cant open it as gradle project, is there sth missing you forgot to push ?
Android studio 1.5.1

**Comment by jemshit** [comment]
ok, downloaded zip and imported. then worked

**Comment by StevenByle** [comment]
@jemshit make sure when importing the project to select the project directory that contains the "app" folder. If you select the root directory of this git project, which has readme files extraneous to the project itself, Android Studio will not find the build.gradle files. That is my guess as to why it wasn't importing.
